### ISSUE TITLE
ValueError: Units 'M', 'Y' and 'y' do not represent unambiguous timedelta...

### ISSUE THREAD

**Issue by luoxiao11** [kasra-keshavarz/metsim-env-narval#2]
the running of "test.conf" {an example provided by metsim} was not successful and some errors show up (see below). I have searched and it seems to be an issue with pandas version (not sure). But the Metsim team has upgraded their version to 2.4.1, which is the Metsim version we are using. I have aso tested and modified the units in Line 66/122  in "disaggregate.py" but the error is still there.
!
![Screen Shot 2023-04-14 at 18 53 03](https://user-images.githubusercontent.com/59952891/232203225-bbd49609-f2ec-49aa-90e7-723dc686cf34.png)

**Comment by luoxiao11** [comment]
I change Line 290 in io.py to " pd.Timedelta('43199 S')).round('D')", and the above error is suppressed. I am not sure if that is the correct way to modify it.

But another error shows up here : "NameError: name 'datetime' is not defined". It looks like "datetime " is not loaded in the environment, and I don't know why "datetime" can be called in this example script if it is not imported.

![Screen Shot 2023-04-16 at 20 45 25](https://user-images.githubusercontent.com/59952891/232405338-c02a3525-d3b3-412b-b455-99cb4b7e79a9.png)

**Comment by kasra-keshavarz** [comment]
Hi Xiao,

Thank you for opening this issue. Here are my suggestion and I hope they could resolve the issue:
1. I notice that the `metsim-env` virtual environment is not activated. After the `create_env.sh` script is run (needs to be run only once), please load the `metsim-mods` modules and then proceed to activate the Python virtual environment that was just built:
```console
[foo@narval ~$]: module restore metsim-mods
[foo@narval ~$]: source $HOME/virtual-envs/metsim-env/bin/activate
```
Once the virtual environment is activated, your shell prompt should look like below:
```console
(metsim-env) [foo@narval ~]$:
```
After the environment has been activated, `MetSim` should run flawlessly. Let me know if there is issue in this step.

2. The `MetSim` default examples need some test data to run. `MetSim`'s own repository have the example's data already. The repository can be downloaded on `Narval`. I typically make a `github-repos` folder in my `$HOME` directory, and then run the following commands:
```console
(metsim-env) [foo@narval ~]$: mkdir ~/github-repos
(metsim-env) [foo@narval ~]$: cd ~/github-repos
(metsim-env) [foo@narval github-repos]$: git clone https://github.com/UW-Hydro/MetSim.git
```
Once the repository is downloaded, please proceed by changing the paths of the given example in the downloaded repository and run `MetSim`. Before that we can switch path to where the `examples` are:

```console
(metsim-env) [foo@narval github-repos]$: cd ~/github-repos/MetSim/examples/
(metsim-env) [foo@narval examples]$: pwd
/home/luox/github-repos/MetSim/examples/
```
You may use `vi` (or any other editors) to change only the following lines of the `example_yaml.yaml` file to the following:

```yaml
MetSim:
    ...
    forcing: '/home/luox/github-repos/MetSim/metsim/data/test.nc'
    domain: '/home/luox/github-repos/MetSim/metsim/data/tiny_domain.nc'
    state: '/home/luox/github-repos/MetSim/metsim/data/state_nc.nc'
    ...
```

After the paths were modified in the `example_yaml.yaml` file, `MetSim` could be run for the example:

```console
(metsim-env) [foo@narval examples]$: mkdir results
(metsim-env) [foo@narval examples]$: chmod 777 results
(metsim-env) [foo@narval examples]$: ms example_yaml.yaml --verbose
```

Once the run is finished, the `bash` prompt should look like the following:

```console
(metsim-env) [foo@narval examples]$: ms example_yaml.yaml --verbose

closed dask cluster/client
```

The results should also be printed under the following directory:

```console
(metsim-env) [foo@narval examples$]: cd results
(metsim-env) [foo@narval results]$: ls -l
total 65
-rw-r-----. 1 luox luox 2943977 Apr 17 11:30 yaml_output_19500101-19500131.nc
```
I hope this resolves the issue. Let me know if you are still getting errors trying to load `metsim`. Cheers!

**Comment by kasra-keshavarz** [comment]
One more suggestion; if you use the Jupyter interface and choose `metsim-mods` and `metsim-env`, all the necessary environments and variables will be loaded and ready to use.

**Comment by luoxiao11** [comment]
> One more suggestion; if you use the Jupyter interface and choose `metsim-mods` and `metsim-env`, all the necessary environments and variables will be loaded and ready to use.

Hi Kasra, Thank you for your suggestion. 
1. I have tiried to follow the instruction from last time to use the Jupyter interface and choose metsim-mods and metsim-env to run in the beginning, but the code can not be executed successfully, that is why then I ran the program through the default terminal.  I might need further assistance with this part:
![Screen Shot 2023-04-17 at 08 10 51](https://user-images.githubusercontent.com/59952891/232573828-e70c68fa-07ec-4d21-b9fc-c6c9eba03ab8.png)


2.Another thing is "$HOME/virtual-envs/metsim-env/bin/activate" can not be found in my home directory.
![Screen Shot 2023-04-17 at 08 10 34](https://user-images.githubusercontent.com/59952891/232574746-2f4d7606-15b7-4ca0-91ad-f692c6e9a685.png)


 If you are free sometime, is it possible for me to present the invoking process, and then maybe you correct me? Besides, since I have modified some part in the script, should I un-install and re-install the software? Thanks in advance!

**Comment by kasra-keshavarz** [comment]
Hi Xiao,

Absolutely! I've already sent you an e-mail for a short meeting today. I can have a short meeting with you anytime today. Cheers.

**Comment by kasra-keshavarz** [comment]
I think the script I've shared has a slight issue, I will double check and update the script here. So hopefully for the future, it will work fine. Thank you for the help in troubleshooting the environment!

**Comment by luoxiao11** [comment]
Many thanks to you, Kasra!

**Comment by kasra-keshavarz** [comment]
Feel free to open other issues if you face difficulty running `MetSim` again. Thanks.
